# Generated by Django 2.1.7 on 2019-04-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_server_trailing_slash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='host',
            field=models.CharField(default='http://127.0.0.1:7000/', max_length=400),
        ),
    ]
